### ISSUE TITLE
'List' feature lists objects not captured by the query

### ISSUE THREAD

**Issue by jamietwells** [SuperpowersCorp/longboye#27]
For example try: 

`/^(\[(?:[A-Za-z])+\])/gm`

Then enter:

`[Captured][NotCaptured][AlsoNotCaptured]`

Then enter in the List box:

 `$1\n` 

Then observe the following incorrect output:

```
[Captured]
[NotCaptured]
[AlsoNotCaptured]
```

**Comment by lgastako** [comment]
Hey I just noticed this.  I think you have the wrong project.
